@echo off

python -m pip install --no-deps torch==2.0.0+cu118 torchvision==0.15.1+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
python -m pip install --no-deps absl-py==1.4.0
python -m pip install --no-deps accelerate==0.20.3
python -m pip install --no-deps addict==2.4.0
python -m pip install --no-deps aiohttp==3.8.4
python -m pip install --no-deps aiosignal==1.3.1
python -m pip install --no-deps albumentations==0.4.3
python -m pip install --no-deps antlr4-python3-runtime==4.8
python -m pip install --no-deps appdirs==1.4.4
python -m pip install --no-deps async-timeout==4.0.2
python -m pip install --no-deps attrs==23.1.0
python -m pip install --no-deps basicsr==1.4.2
python -m pip install --no-deps boltons==23.0.0
python -m pip install --no-deps cachetools==5.3.1
python -m pip install --no-deps certifi==2023.5.7
python -m pip install --no-deps charset-normalizer==3.1.0
python -m pip install --no-deps clean-fid==0.1.35
python -m pip install --no-deps click==8.1.3
python -m pip install --no-deps git+https://github.com/openai/CLIP.git@a9b1bf5920416aaeaec965c25dd9e8f98c864f16
python -m pip install --no-deps clip-anytorch==2.5.2
python -m pip install --no-deps git+https://github.com/invoke-ai/clipseg.git@1f754751c85d7d4255fa681f4491ff5711c1c288
python -m pip install --no-deps colorama==0.4.6
python -m pip install --no-deps coloredlogs==15.0.1
python -m pip install --no-deps compel==1.1.6
python -m pip install --no-deps contourpy==1.0.7
python -m pip install --no-deps cycler==0.11.0
python -m pip install --no-deps diffusers==0.16.1
python -m pip install --no-deps dill==0.3.6
python -m pip install --no-deps dnspython==2.2.1
python -m pip install --no-deps docker-pycreds==0.4.0
python -m pip install --no-deps einops==0.6.0
python -m pip install --no-deps facexlib==0.3.0
python -m pip install --no-deps filelock==3.12.1
python -m pip install --no-deps filterpy==1.4.5
python -m pip install --no-deps flatbuffers==23.5.26
python -m pip install --no-deps fonttools==4.39.4
python -m pip install --no-deps frozenlist==1.3.3
python -m pip install --no-deps fsspec==2023.6.0
python -m pip install --no-deps ftfy==6.1.1
python -m pip install --no-deps future==0.18.3
python -m pip install --no-deps gfpgan==1.3.8
python -m pip install --no-deps gitdb==4.0.10
python -m pip install --no-deps GitPython==3.1.31
python -m pip install --no-deps google-auth==2.19.1
python -m pip install --no-deps google-auth-oauthlib==1.0.0
python -m pip install --no-deps grpcio==1.54.2
python -m pip install --no-deps huggingface-hub==0.15.1
python -m pip install --no-deps humanfriendly==10.0
python -m pip install --no-deps idna==3.4
python -m pip install --no-deps imageio==2.31.0
python -m pip install --no-deps imgaug==0.2.6
python -m pip install --no-deps importlib-metadata==6.6.0
python -m pip install --no-deps Jinja2==3.1.2
python -m pip install --no-deps jsonmerge==1.9.0
python -m pip install --no-deps jsonschema==4.17.3
python -m pip install --no-deps kiwisolver==1.4.4
python -m pip install --no-deps kornia==0.6.12
python -m pip install --no-deps lazy_loader==0.2
python -m pip install --no-deps lmdb==1.4.1
python -m pip install --no-deps Markdown==3.4.3
python -m pip install --no-deps markdown-it-py==2.2.0
python -m pip install --no-deps MarkupSafe==2.1.3
python -m pip install --no-deps mdurl==0.1.2
python -m pip install --no-deps mpmath==1.3.0
python -m pip install --no-deps multidict==6.0.4
python -m pip install --no-deps multiprocess==0.70.14
python -m pip install --no-deps networkx==3.1
python -m pip install --no-deps npyscreen==4.10.5
python -m pip install --no-deps numba==0.57.0
python -m pip install --no-deps numpy==1.23.4
python -m pip install --no-deps oauthlib==3.2.2
python -m pip install --no-deps omegaconf==2.1.1
python -m pip install --no-deps onnx==1.13.0
python -m pip install --no-deps onnxruntime==1.13.1
python -m pip install --no-deps onnxruntime-directml==1.13.1
python -m pip install --no-deps opencv-python==4.5.5.64
python -m pip install --no-deps opencv-python-headless==4.7.0.72
python -m pip install --no-deps packaging==23.1
python -m pip install --no-deps pandas==2.0.2
python -m pip install --no-deps pathtools==0.1.2
python -m pip install --no-deps peft==0.3.0
python -m pip install --no-deps picklescan==0.0.5
python -m pip install --no-deps Pillow==9.2.0
python -m pip install --no-deps prompt-toolkit==3.0.38
python -m pip install --no-deps protobuf==3.20.1
python -m pip install --no-deps psutil==5.9.5
python -m pip install --no-deps pyasn1==0.5.0
python -m pip install --no-deps pyasn1-modules==0.3.0
python -m pip install --no-deps pyDeprecate==0.3.2
python -m pip install --no-deps Pygments==2.15.1
python -m pip install --no-deps pyparsing==3.0.9
python -m pip install --no-deps PyPatchMatch==1.0.0
python -m pip install --no-deps pyreadline3==3.4.1
python -m pip install --no-deps pyrsistent==0.19.3
python -m pip install --no-deps python-dateutil==2.8.2
python -m pip install --no-deps pytorch-lightning==1.6.5
python -m pip install --no-deps pytz==2023.3
python -m pip install --no-deps PyWavelets==1.4.1
python -m pip install --no-deps PyYAML==6.0
python -m pip install --no-deps realesrgan==0.3.0
python -m pip install --no-deps regex==2023.6.3
python -m pip install --no-deps requests==2.28.2
python -m pip install --no-deps requests-oauthlib==1.3.1
python -m pip install --no-deps resize-right==0.0.2
python -m pip install --no-deps responses==0.18.0
python -m pip install --no-deps rich==13.4.1
python -m pip install --no-deps rsa==4.9
python -m pip install --no-deps safetensors==0.3.1
python -m pip install --no-deps scikit-image==0.21.0
python -m pip install --no-deps scipy==1.10.1
python -m pip install --no-deps sentry-sdk==1.25.1
python -m pip install --no-deps setproctitle==1.3.2
python -m pip install --no-deps six==1.16.0
python -m pip install --no-deps smmap==5.0.0
python -m pip install --no-deps sympy==1.12
python -m pip install --no-deps taming-transformers-rom1504==0.0.6
python -m pip install --no-deps tb-nightly==2.14.0a20230610
python -m pip install --no-deps tensorboard==2.13.0
python -m pip install --no-deps tensorboard-data-server==0.7.0
python -m pip install --no-deps test-tube==0.7.5
python -m pip install --no-deps tifffile==2023.4.12
python -m pip install --no-deps tokenizers==0.13.3
python -m pip install --no-deps tomli==2.0.1
python -m pip install --no-deps torch-fidelity==0.3.0
python -m pip install --no-deps torchdiffeq==0.2.3
python -m pip install --no-deps torchmetrics==0.6.0
python -m pip install --no-deps torchsde==0.2.5
python -m pip install --no-deps tqdm==4.65.0
python -m pip install --no-deps trampoline==0.1.2
python -m pip install --no-deps transformers==4.29.2
python -m pip install --no-deps typing_extensions==4.6.3
python -m pip install --no-deps tzdata==2023.3
python -m pip install --no-deps urllib3==1.26.16
python -m pip install --no-deps wandb==0.15.4
python -m pip install --no-deps wcwidth==0.2.6
python -m pip install --no-deps Werkzeug==2.3.6
python -m pip install --no-deps xxhash==3.2.0
python -m pip install --no-deps yapf==0.33.0
python -m pip install --no-deps yarl==1.9.2
python -m pip install --no-deps zipp==3.15.0
python -m pip install --no-deps k-diffusion==0.0.15
python -m pip install --no-deps voluptuous==0.13.1
python -m pip install --no-deps lycoris-lora==0.1.5
python -m pip install --no-deps toml==0.10.2
python -m pip install --no-deps ./repo/src/InvokeAI-2.3.5